
export const USER_AVATAR_CATEGORY = "user-avatar";
export const USER_BANNER_CATEGORY = "user-banner";


export enum CATEGORY_PROCESS {
    USER_AVATAR = "user-avatar",
    USER_BANNER = "user-banner",
    DOCUMENT_DTE = "DTE-factura",
}

export enum EVENT_CODES{
    FACTURA_PUBLICADA = "FACTURA_PUBLICADA",
    FACTURA_VACIA_PUBLICADA = "FACTURA_VACIA_PUBLICADA",
    FACTURA_DUPLICADA = "FACTURA_DUPLICADA",
    FACTURA_PROCESADA = "FACTURA_PROCESADA",
    FACTURA_ERROR_PROCESAMIENTO = "FACTURA_ERROR_PROCESAMIENTO",
}

export enum facturaEstado {
    PENDIENTE_VALIDACION = "PENDIENTE_VALIDACION",
    PUBLICADA = "PUBLICADA",
    OFERTADA = "OFERTADA",
    FINANCIADA = "FINANCIADA",
    PAGADA = "PAGADA",
    RECHAZADA = "RECHAZADA",
    CANCELADA = "CANCELADA",
    VENCIDA = "VENCIDA",
    DENUNCIADA = "DENUNCIADA",
}